apiVersion: v1
kind: Pod
metadata:
  name: 
  namespace: my-app
  labels:
    abc: ded
    notused: remove-me
spec:
  containers:
    - image: alpine:3.18
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always