name: devcontainer-ci-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/devcontainer-ci/example-devcontainer
          cacheFrom: ghcr.io/devcontainer-ci/example-devcontainer
          push: always
      - uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/devcontainer-ci/example-devcontainer
          push: never
          runCmd: idpbuilder create --package-dir ./examples/ack
