name: devcontainer-ci-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -al
      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aatchison/features/idpbuilder:2.0.0
          cacheFrom: ghcr.io/aatchison/features/idpbuilder:2.0.0
          push: always